### ISSUE TITLE
异常:ModuleNotFoundError: No module named 'wechat_ocr.ocr_manager'; 'wechat_ocr' is not a package是怎么回事？

### ISSUE THREAD

**Issue by L-T-Z** [kanadeblisst00/wechat_ocr#13]
![Uploading image.png…]()
Traceback (most recent call last):
  File ".\wechat_ocr.py", line 4, in <module>
    from wechat_ocr.ocr_manager import OcrManager, OCR_MAX_TASK_ID
  File "D:\project\wechat_ocr\wechat_ocr.py", line 4, in <module>
    from wechat_ocr.ocr_manager import OcrManager, OCR_MAX_TASK_ID
ModuleNotFoundError: No module named 'wechat_ocr.ocr_manager'; 'wechat_ocr' is not a package

**Comment by NOBB2333** [comment]
把 包的路径使用 sys.path  添加进去试试

**Comment by L-T-Z** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by L-T-Z** [comment]
> 把 包的路径使用 sys.path 添加进去试试
`package_path = r"D:\SoftwarePackage\python\Lib\site-packages\wechat_ocr"
sys.path.append(package_path)

from wechat_ocr.ocr_manager import OcrManager, OCR_MAX_TASK_ID`
异常信息:
Traceback (most recent call last):
  File ".\wechat_ocr.py", line 9, in <module>
    from wechat_ocr.ocr_manager import OcrManager, OCR_MAX_TASK_ID
  File "D:\project\wechat_ocr\wechat_ocr.py", line 9, in <module>
    from wechat_ocr.ocr_manager import OcrManager, OCR_MAX_TASK_ID
ModuleNotFoundError: No module named 'wechat_ocr.ocr_manager'; 'wechat_ocr' is not a package

还是不行

**Comment by NOBB2333** [comment]
[site-packages (2).zip](https://github.com/user-attachments/files/16346085/site-packages.2.zip)

**Comment by L-T-Z** [comment]
> [site-packages (2).zip](https://github.com/user-attachments/files/16346085/site-packages.2.zip)

直接把包的源码复制过来可行, 但为什么安装的包会出现这样的异常呀?

**Comment by H1d3rOne** [comment]
是不是包名和本地文件同名了

**Comment by L-T-Z** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
